version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_DOCKER_TAG}
    container_name: 'rabbitmq'
    ports:
        - ${RABBITMQ_PORT}:5672
        - ${RABBITMQ_WEB_PORT}:15672
    volumes:
        - ${RABBITMQ_DEFAULT_DATA_VOLUMN}:/var/lib/rabbitmq/
        - ${RABBITMQ_DEFAULT_LOG_VOLUMN}:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

networks:
  rabbitmq_go_net:
    driver: bridge


# `RAM_NODE` ref please check https://github.com/kailashyogeshwar85/docker-rabbitmq-cluster/blob/be440316dd9747667af913f67911bcafa610fbc0/server/startrabbit.sh 
# at line 44 
#
# [-z $VAR] return `True` if VAR is null
