version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_DOCKER_TAG}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_WEB_PORT}:15672
    volumes:
      - ${RABBITMQ_VOLUMN}/${RABBITMQ_CONTAINER_NAME}/data/:/var/lib/rabbitmq/
      - ${RABBITMQ_VOLUMN}/${RABBITMQ_CONTAINER_NAME}/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

networks:
  rabbitmq_go_net:
    driver: bridge


# `RAM_NODE` ref please check https://github.com/kailashyogeshwar85/docker-rabbitmq-cluster/blob/be440316dd9747667af913f67911bcafa610fbc0/server/startrabbit.sh 
# at line 44 
#
# [-z $VAR] return `True` if VAR is null

# Error while log/ permission error
# https://github.com/docker-library/rabbitmq/issues/530
# `$ cd <volume_path>/`
# `$ sudo chown -R systemd-network:root log/`
